version: "3"

services:
  https-portal:
    image: steveltn/https-portal:1
    ports:
      - '80:80'
      - '443:443'
    links:
      - web
    restart: always
    networks:
      - external_network
      - internal_network
    environment:
      DOMAINS: 'misskey.tebukuro.xyz -> http://web:3000, files.misskey.tebukuro.xyz -> http://web:3000'
      # STAGE: 'production'
      WEBSOCKET: 'true'
      # FORCE_RENEW: 'true'
    volumes:
      - ./.config/nginx:/var/lib/nginx-conf/files.misskey.tebukuro.xyz.ssl.conf.erb:ro

  web:
    build: .
    restart: always
    links:
      - db
      - redis
      #  - es
    expose:
      - 3000
    networks:
      - internal_network
      - external_network
    volumes:
      - ./files:/misskey/files

  redis:
    restart: always
    image: redis:4.0-alpine
    networks:
      - internal_network
    volumes:
      - ./redis:/data

  db:
    restart: always
    image: postgres:12.2-alpine
    networks:
      - internal_network
    env_file:
      - .config/docker.env
    volumes:
      - ./db:/var/lib/postgresql/data

 # es:
 #   restart: always
 #   image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.4.2
 #   environment:
 #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
 #   networks:
 #     - internal_network
 #   volumes:
 #     - ./elasticsearch:/usr/share/elasticsearch/data

networks:
  internal_network:
    internal: true
  external_network:
